#!/bin/bash

NBMIN=0
NBMAX=10
NFRAMES=3
NSTEPS=$(( ($NBMAX - $NBMIN) / $NFRAMES ))

echo $NSTEPS
for foo in $(seq 0 $NFRAMES )
do
  echo "$foo" 
  echo "NB=${NBMIN}+${foo}*(${NBMAX}-${NBMIN})/${NFRAMES}"
done
